/**
 * a Web-based CNF-SAT solver. This manages the files.
 * Stores the files in DIMACS format
 */
function download(){
    let cnf = getCNFData();
    let variables = []
    for(let i = 0; i<cnf.length; i++){
        for(let j = 0; j<cnf[i].length; j++){
            if(!variables.includes(cnf[i][j].v)){
                variables.push(cnf[i][j].v)
            }
        }
    }
    let stringData = `c generated by TJ Nickerson's CNF-SAT editor\np cnf ${variables.length} ${cnf.length}`
    for(let i = 0; i<cnf.length; i++){
        stringData += "\n"
        for(let j = 0; j<cnf[i].length; j++){
            stringData += (cnf[i][j].n ? "" : "-") + (variables.indexOf(cnf[i][j].v)+1) + " "
        }
        stringData += "0"
    }
    downloadFile(stringData)
    //prep file for download
}
/**
 * Not my code. Downloads the file, given in string format
 * @param {String} data The text data to download
 * https://stackoverflow.com/questions/13405129/create-and-save-a-file-with-javascript
 */
function downloadFile(data) {
    let currDate = new Date();
    let filename = `formula-${currDate.getMonth()+1}-${currDate.getDate()}.cnf`
    var file = new Blob([data], {type: "cnf"});
    if (window.navigator.msSaveOrOpenBlob) // IE10+
        window.navigator.msSaveOrOpenBlob(file, filename);
    else { // Others
        var a = document.createElement("a"),
                url = URL.createObjectURL(file);
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        setTimeout(function() {
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);  
        }, 0); 
    }
}
