export default class Save{

BASE_COLONY_ATTACK = 1;
BASE_COLONY_DEFENSE = 1;
BASE_COLONY_MILSTRENGTH = 1;

BASE_COLONY_REC_PERC = .015;
BASE_COLONY_POP_GROWTH = 1.5;
BASE_COLONY_EXPAND_RATE = 100;

TILE_POP_GROWTH = .04;
TILE_EXPAND_RATE = 100;
TILE_RECRUIT_PERC = .015


constructor(){}

}